### ISSUE TITLE
source of solar-system

### ISSUE THREAD

**Issue by mfuchs1** [lvmaoa/Gruvbox-Wallpapers#1]
Hello @lvmaoa 
can you give me the source of that wonderful image "solar-system", please?
I've found this website https://ninedegreesbelow.com/ ... I think Elle Stone (owner of this website) is the author of that image. I've found her name and her website in the metadata of that image.

Thanks a lot.
Matthias Fuchs

**Comment by lvmaoa** [comment]
Hey Matthais, 

I actually found the wallpaper [here](https://github.com/FrenzyExists/wallpapers/blob/main/Gruv/solar-system.jpg ) so it might be better to ask the owner of the website or [FrenzyExists](https://github.com/FrenzyExists). 

Thanks,
@lvmaoa
